/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  docs: [
    {
      type: 'autogenerated',
      dirName: '.', // generate sidebar from docs folder (root)
    },
  ],
};
module.exports = sidebars;
