apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: navlambda-backend-hpa
  namespace: navlambda-studio
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: navlambda-backend
  minReplicas: 1
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
  - type: External
    external:
      metric:
        name: navlambda_requests_per_second
        selector:
          matchLabels:
            service: navlambda-backend
      target:
        type: Value
        value: "100"
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: navlambda-frontend-hpa
  namespace: navlambda-studio
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: navlambda-frontend
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70